### ISSUE TITLE
What's the best way of running this ?

### ISSUE THREAD

**Issue by stuaxo** [D-P1R5N/Terrain_Gen#1]
Does this need to be run in the Jupyter notebook ?

**Comment by D-P1R5N** [comment]
I haven't really used Jupyter Notebook so I am not sure. There's still some
stuff I need to learn how to do for sharing code, but it was written in an
IDE (Atom).

**Comment by stuaxo** [comment]
Cheers.

I think I saw the plot commands and made an assumption.
